In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# House Price Prediction System

In [3]:
df=pd.read_csv('bangalore house price prediction.csv')
df

,bath,balcony,price,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
0,3.0,2.0,150.00,1672.0,3,8971.291866,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,3.0,3.0,149.00,1750.0,3,8514.285714,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0
2,3.0,2.0,150.00,1750.0,3,8571.428571,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,2.0,2.0,40.00,1250.0,2,3200.000000,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,2.0,2.0,83.00,1200.0,2,6916.666667,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7115,3.0,2.0,325.00,2900.0,3,11206.896552,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7116,3.0,1.0,84.83,1780.0,3,4765.730337,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7117,2.0,1.0,48.00,880.0,2,5454.545455,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
7118,2.0,1.0,55.00,1000.0,2,5500.000000,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
7119,2.0,1.0,78.00,1400.0,3,5571.428571,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
df.shape

(7120, 108)

In [5]:
df.dtypes

bath                           float64
balcony                        float64
price                          float64
total_sqft_int                 float64
bhk                              int64
                                ...
location_Hosur Road              int64
location_Horamavu Banaswadi      int64
location_Domlur                  int64
location_Mahadevpura             int64
location_Tumkur Road             int64
Length: 108, dtype: object

In [6]:
df.isnull().sum()

bath                           0
balcony                        0
price                          0
total_sqft_int                 0
bhk                            0
                              ..
location_Hosur Road            0
location_Horamavu Banaswadi    0
location_Domlur                0
location_Mahadevpura           0
location_Tumkur Road           0
Length: 108, dtype: int64

In [7]:
df.duplicated().sum()

np.int64(467)

In [8]:
df.drop_duplicates(inplace=True, ignore_index=True)

In [9]:
df.shape, df.duplicated().sum()

((6653, 108), np.int64(0))

In [10]:
df.dtypes

bath                           float64
balcony                        float64
price                          float64
total_sqft_int                 float64
bhk                              int64
                                ...
location_Hosur Road              int64
location_Horamavu Banaswadi      int64
location_Domlur                  int64
location_Mahadevpura             int64
location_Tumkur Road             int64
Length: 108, dtype: object

In [11]:
df.describe()

,bath,balcony,price,total_sqft_int,bhk,price_per_sqft,area_typeSuper built-up Area,area_typeBuilt-up Area,area_typePlot Area,availability_Ready To Move,...,location_Kalena Agrahara,location_Horamavu Agara,location_Vidyaranyapura,location_BTM 2nd Stage,location_Hebbal Kempapura,location_Hosur Road,location_Horamavu Banaswadi,location_Domlur,location_Mahadevpura,location_Tumkur Road
count,6653.000000,6653.000000,6653.000000,6653.000000,6653.000000,6653.000000,6653.000000,6653.000000,6653.000000,6653.000000,...,6653.000000,6653.000000,6653.000000,6653.000000,6653.000000,6653.000000,6653.000000,6653.000000,6653.000000,6653.000000
mean,2.405531,1.574547,98.526354,1493.784366,2.478731,5988.520536,0.739666,0.192094,0.062829,0.797986,...,0.003307,0.003156,0.002856,0.003156,0.003156,0.003006,0.002555,0.003006,0.002856,0.003006
std,0.889901,0.780230,119.463425,937.445496,0.854073,2601.134298,0.438850,0.393976,0.242673,0.401533,...,0.057414,0.056098,0.053368,0.056098,0.056098,0.054750,0.050489,0.054750,0.053368,0.054750
min,1.000000,0.000000,10.000000,350.000000,1.000000,1250.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2.000000,1.000000,50.000000,1100.000000,2.000000,4464.285714,0.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2.000000,2.000000,70.000000,1265.000000,2.000000,5477.424130,1.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,3.000000,2.000000,105.000000,1654.000000,3.000000,6666.666667,1.000000,0.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,9.000000,3.000000,2912.000000,30400.000000,9.000000,35000.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [12]:
df.columns

Index(['bath', 'balcony', 'price', 'total_sqft_int', 'bhk', 'price_per_sqft',
       'area_typeSuper built-up  Area', 'area_typeBuilt-up  Area',
       'area_typePlot  Area', 'availability_Ready To Move',
       ...
       'location_Kalena Agrahara', 'location_Horamavu Agara',
       'location_Vidyaranyapura', 'location_BTM 2nd Stage',
       'location_Hebbal Kempapura', 'location_Hosur Road',
       'location_Horamavu Banaswadi', 'location_Domlur',
       'location_Mahadevpura', 'location_Tumkur Road'],
      dtype='object', length=108)

In [13]:
X=df.drop('price', axis=1)
y=df['price']

In [14]:
X, y

(      bath   balcony  total_sqft_int  bhk  price_per_sqft  \
 0      3.0  2.000000          1672.0    3     8971.291866
 1      3.0  3.000000          1750.0    3     8514.285714
 2      3.0  2.000000          1750.0    3     8571.428571
 3      2.0  2.000000          1250.0    2     3200.000000
 4      2.0  2.000000          1200.0    2     6916.666667
 ...    ...       ...             ...  ...             ...
 6648   6.0  1.584376          3800.0    6    10263.157895
 6649   3.0  2.000000          2900.0    3    11206.896552
 6650   3.0  1.000000          1780.0    3     4765.730337
 6651   2.0  1.000000           880.0    2     5454.545455
 6652   2.0  1.000000          1400.0    3     5571.428571

       area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
 0                                 1                        0
 1                                 0                        1
 2                                 1                        0
 3                                 1                        0
 4                                 0                        0
 ...                             ...                      ...
 6648                              1                        0
 6649                              1                        0
 6650                              1                        0
 6651                              0                        0
 6652                              0                        0

       area_typePlot  Area  availability_Ready To Move  location_Whitefield  \
 0                       0                           1                    0
 1                       0                           1                    0
 2                       0                           1                    0
 3                       0                           1                    0
 4                       1                           1                    0
 ...                   ...                         ...                  ...
 6648                    0                           1                    0
 6649                    0                           1                    0
 6650                    0                           0                    0
 6651                    1                           1                    0
 6652                    1                           0                    0

       ...  location_Kalena Agrahara  location_Horamavu Agara  \
 0     ...                         0                        0
 1     ...                         0                        0
 2     ...                         0                        0
 3     ...                         0                        0
 4     ...                         0                        0
 ...   ...                       ...                      ...
 6648  ...                         0                        0
 6649  ...                         0                        0
 6650  ...                         0                        0
 6651  ...                         0                        0
 6652  ...                         0                        0

       location_Vidyaranyapura  location_BTM 2nd Stage  \
 0                           0                       0
 1                           0                       0
 2                           0                       0
 3                           0                       0
 4                           0                       0
 ...                       ...                     ...
 6648                        0                       0
 6649                        0                       0
 6650                        0                       0
 6651                        0                       0
 6652                        0                       0

       location_Hebbal Kempapura  location_Hosur Road  \
 0                             0                    0
 1                             0                    0
 2                             0                    0
 3                             0                    0
 4                             0                    0
 ...                         ...                  ...
 6648                          0                    0
 6649                          0                    0
 6650                          0                    0
 6651                          0                    0
 6652                          0                    0

       location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
 0                               0                0                     0
 1                               0                0                     0
 2                               0                0                     0
 3                               0                0                     0
 4                               0                0                     0
 ...                           ...              ...                   ...
 6648                            0                0                     0
 6649                            0                0                     0
 6650                            0                0                     0
 6651                            0                0                     0
 6652                            0                0                     0

       location_Tumkur Road
 0                        0
 1                        0
 2                        0
 3                        0
 4                        0
 ...                    ...
 6648                     0
 6649                     0
 6650                     0
 6651                     0
 6652                     0

 [6653 rows x 107 columns],
 0       150.00
 1       149.00
 2       150.00
 3        40.00
 4        83.00
          ...
 6648    390.00
 6649    325.00
 6650     84.83
 6651     48.00
 6652     78.00
 Name: price, Length: 6653, dtype: float64)

In [15]:
# scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [16]:
sc.fit(X)
X_sc=sc.transform(X)

In [17]:
# train test split
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test=train_test_split(X_sc, y, test_size=0.2, random_state=11)

In [19]:
X_train.shape, y_train.shape

((5322, 107), (5322,))

In [20]:
X_test.shape, y_test.shape

((1331, 107), (1331,))

In [21]:
# model training
from sklearn.linear_model import LinearRegression
reg=LinearRegression()

In [22]:
reg.fit(X_train, y_train)

LinearRegression()

In [23]:
reg.score(X_test, y_test)

0.8766351617363195

In [24]:
y_pred=reg.predict(X_test)

In [25]:
op=pd.DataFrame({'y_test / actual o/p':y_test, 'y_pred/ pred o/p':y_pred})
op

      y_test / actual o/p  y_pred/ pred o/p
4486               50.855         52.877203
2873              115.000        143.952753
1517               69.000         74.620373
1005               47.100         24.529427
2401               85.000         86.444653
...                   ...               ...
6049               56.120         54.302079
2083               66.000         68.051767
5804              107.000        105.647545
4089              120.000        138.113490
3170               49.500         32.620628

[1331 rows x 2 columns]

In [26]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [27]:
mean_absolute_error(y_test, y_pred)

18.414346687812643

In [28]:
mean_squared_error(y_test, y_pred)**0.5

42.5869173895491

In [29]:
r2_score(y_test, y_pred)

0.8766351617363195

## Car Price Prediction System

In [30]:
df=pd.read_csv('car data.csv')
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [31]:
df.shape

(301, 9)

In [32]:
df.dtypes

Car_Name          object
Year               int64
Selling_Price    float64
Present_Price    float64
Kms_Driven         int64
Fuel_Type         object
Seller_Type       object
Transmission      object
Owner              int64
dtype: object

In [33]:
df.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [34]:
df.duplicated().sum()

np.int64(2)

In [35]:
df.drop_duplicates(inplace=True, ignore_index=True)

In [36]:
df.shape, df.duplicated().sum()

((299, 9), np.int64(0))

In [37]:
df['no_of_year']=2025-df['Year']

In [38]:
df.drop('Year', inplace=True, axis=1)

In [39]:
df.head()

,Car_Name,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,no_of_year
0,ritz,3.35,5.59,27000,Petrol,Dealer,Manual,0,11
1,sx4,4.75,9.54,43000,Diesel,Dealer,Manual,0,12
2,ciaz,7.25,9.85,6900,Petrol,Dealer,Manual,0,8
3,wagon r,2.85,4.15,5200,Petrol,Dealer,Manual,0,14
4,swift,4.60,6.87,42450,Diesel,Dealer,Manual,0,11

In [40]:
X=df.drop(['Car_Name', 'Selling_Price'], axis=1)
y=df['Selling_Price']

In [41]:
X, y

(     Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner  \
 0             5.59       27000    Petrol      Dealer       Manual      0
 1             9.54       43000    Diesel      Dealer       Manual      0
 2             9.85        6900    Petrol      Dealer       Manual      0
 3             4.15        5200    Petrol      Dealer       Manual      0
 4             6.87       42450    Diesel      Dealer       Manual      0
 ..             ...         ...       ...         ...          ...    ...
 294          11.60       33988    Diesel      Dealer       Manual      0
 295           5.90       60000    Petrol      Dealer       Manual      0
 296          11.00       87934    Petrol      Dealer       Manual      0
 297          12.50        9000    Diesel      Dealer       Manual      0
 298           5.90        5464    Petrol      Dealer       Manual      0

      no_of_year
 0            11
 1            12
 2             8
 3            14
 4            11
 ..          ...
 294           9
 295          10
 296          16
 297           8
 298           9

 [299 rows x 7 columns],
 0       3.35
 1       4.75
 2       7.25
 3       2.85
 4       4.60
        ...
 294     9.50
 295     4.00
 296     3.35
 297    11.50
 298     5.30
 Name: Selling_Price, Length: 299, dtype: float64)

In [42]:
from sklearn.preprocessing import OneHotEncoder
oh=OneHotEncoder(sparse_output=False)

In [43]:
df['Fuel_Type'].value_counts()

Fuel_Type
Petrol    239
Diesel     58
CNG         2
Name: count, dtype: int64

In [44]:
df['Seller_Type'].value_counts()

Seller_Type
Dealer        193
Individual    106
Name: count, dtype: int64

In [45]:
df['Transmission'].value_counts()

Transmission
Manual       260
Automatic     39
Name: count, dtype: int64

In [46]:
en=oh.fit_transform(X[['Fuel_Type', 'Seller_Type', 'Transmission']])
en

array([[0., 0., 1., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 1.],
       ...,
       [0., 0., 1., ..., 0., 0., 1.],
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 1.]])

In [47]:
b=oh.get_feature_names_out()
b

array(['Fuel_Type_CNG', 'Fuel_Type_Diesel', 'Fuel_Type_Petrol',
       'Seller_Type_Dealer', 'Seller_Type_Individual',
       'Transmission_Automatic', 'Transmission_Manual'], dtype=object)

In [48]:
# X['x0_Fuel_Type', 'x1_Seller_Type', 'x2_Transmission'] = oh.fit_transform([['Fuel_Type', 'Seller_Type', 'Transmission']])
X[b]=en

In [49]:
X[b]

,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Dealer,Seller_Type_Individual,Transmission_Automatic,Transmission_Manual
0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
1,0.0,1.0,0.0,1.0,0.0,0.0,1.0
2,0.0,0.0,1.0,1.0,0.0,0.0,1.0
3,0.0,0.0,1.0,1.0,0.0,0.0,1.0
4,0.0,1.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...
294,0.0,1.0,0.0,1.0,0.0,0.0,1.0
295,0.0,0.0,1.0,1.0,0.0,0.0,1.0
296,0.0,0.0,1.0,1.0,0.0,0.0,1.0
297,0.0,1.0,0.0,1.0,0.0,0.0,1.0
298,0.0,0.0,1.0,1.0,0.0,0.0,1.0

In [50]:
X.drop(['Seller_Type', 'Fuel_Type', 'Transmission'], inplace=True, axis=1)

In [51]:
X

,Present_Price,Kms_Driven,Owner,no_of_year,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Dealer,Seller_Type_Individual,Transmission_Automatic,Transmission_Manual
0,5.59,27000,0,11,0.0,0.0,1.0,1.0,0.0,0.0,1.0
1,9.54,43000,0,12,0.0,1.0,0.0,1.0,0.0,0.0,1.0
2,9.85,6900,0,8,0.0,0.0,1.0,1.0,0.0,0.0,1.0
3,4.15,5200,0,14,0.0,0.0,1.0,1.0,0.0,0.0,1.0
4,6.87,42450,0,11,0.0,1.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
294,11.60,33988,0,9,0.0,1.0,0.0,1.0,0.0,0.0,1.0
295,5.90,60000,0,10,0.0,0.0,1.0,1.0,0.0,0.0,1.0
296,11.00,87934,0,16,0.0,0.0,1.0,1.0,0.0,0.0,1.0
297,12.50,9000,0,8,0.0,1.0,0.0,1.0,0.0,0.0,1.0
298,5.90,5464,0,9,0.0,0.0,1.0,1.0,0.0,0.0,1.0

In [52]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [53]:
X.columns

Index(['Present_Price', 'Kms_Driven', 'Owner', 'no_of_year', 'Fuel_Type_CNG',
       'Fuel_Type_Diesel', 'Fuel_Type_Petrol', 'Seller_Type_Dealer',
       'Seller_Type_Individual', 'Transmission_Automatic',
       'Transmission_Manual'],
      dtype='object')

In [54]:
X[['no_of_year', 'Present_Price', 'Kms_Driven']]=sc.fit_transform(X[['no_of_year', 'Present_Price', 'Kms_Driven']])

In [55]:
X

,Present_Price,Kms_Driven,Owner,no_of_year,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Dealer,Seller_Type_Individual,Transmission_Automatic,Transmission_Manual
0,-0.228097,-0.254603,0,-0.132992,0.0,0.0,1.0,1.0,0.0,0.0,1.0
1,0.233700,0.156181,0,0.212787,0.0,1.0,0.0,1.0,0.0,0.0,1.0
2,0.269942,-0.770651,0,-1.170329,0.0,0.0,1.0,1.0,0.0,0.0,1.0
3,-0.396448,-0.814297,0,0.904345,0.0,0.0,1.0,1.0,0.0,0.0,1.0
4,-0.078451,0.142061,0,-0.132992,0.0,1.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
294,0.474536,-0.075193,0,-0.824550,0.0,1.0,0.0,1.0,0.0,0.0,1.0
295,-0.191855,0.592640,0,-0.478771,0.0,0.0,1.0,1.0,0.0,0.0,1.0
296,0.404389,1.309818,0,1.595904,0.0,0.0,1.0,1.0,0.0,0.0,1.0
297,0.579755,-0.716735,0,-1.170329,0.0,1.0,0.0,1.0,0.0,0.0,1.0
298,-0.191855,-0.807519,0,-0.824550,0.0,0.0,1.0,1.0,0.0,0.0,1.0

In [56]:
X.describe()

,Present_Price,Kms_Driven,Owner,no_of_year,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Dealer,Seller_Type_Individual,Transmission_Automatic,Transmission_Manual
count,2.990000e+02,2.990000e+02,299.000000,2.990000e+02,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000,299.000000
mean,4.752794e-17,-4.158695e-17,0.043478,-1.128789e-16,0.006689,0.193980,0.799331,0.645485,0.354515,0.130435,0.869565
std,1.001676e+00,1.001676e+00,0.248720,1.001676e+00,0.081649,0.396076,0.401172,0.479168,0.479168,0.337346,0.337346
min,-8.442155e-01,-9.349646e-01,0.000000,-1.516109e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,-7.413342e-01,-5.626912e-01,0.000000,-8.245502e-01,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
50%,-1.684724e-01,-1.262328e-01,0.000000,-1.329920e-01,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000
75%,2.687731e-01,3.072346e-01,0.000000,5.585663e-01,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000
max,9.944291e+00,1.188921e+01,3.000000,3.670579e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [57]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=11)

In [58]:
X_train.shape, X_test.shape

((239, 11), (60, 11))

In [59]:
y_train.shape, y_test.shape

((239,), (60,))

In [60]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()

In [61]:
reg.fit(X_train, y_train)

LinearRegression()

In [62]:
reg.score(X_test, y_test)

0.8940032895151809

In [63]:
y_pred=reg.predict(X_test)
y_pred

array([ 5.9814207 , 10.9660479 ,  4.43466868,  7.88637405,  4.22632741,
        0.67600203,  7.82548576,  1.05852146, 10.41006917,  6.34786997,
        9.31253986,  6.70403606, -1.04744066,  2.57922785,  0.33674571,
        4.28303503, 20.08046381,  6.70494326,  5.10769506,  6.94970883,
        4.24750485,  1.24788647,  7.26847248,  8.04688868,  1.50937192,
       -1.18084793,  0.14137591,  1.38964606,  9.91135421,  1.86702544,
        2.25149673,  7.31326122,  3.37999003,  1.69156111,  5.34259311,
        7.4264317 ,  2.16809914, 20.6704929 ,  1.6602934 , -0.51793824,
       -0.0404171 ,  4.20846555,  7.67724866,  0.24255825,  9.14597907,
        5.59855182, -2.6670233 ,  4.26021269,  8.33360221, -0.91806012,
        1.91886494,  0.99814604,  9.67636734,  6.38595672, -1.0581031 ,
       15.81683161,  2.57367686,  2.80329904,  7.65638326,  1.96259525])

In [64]:
pd.DataFrame({'y_test':y_test, 'y_pred':y_pred})

     y_test     y_pred
69     3.95   5.981421
77     5.25  10.966048
278    5.25   4.434669
254   10.25   7.886374
260    4.00   4.226327
53     2.75   0.676002
12     7.50   7.825486
179    0.30   1.058521
97     9.65  10.410069
86     5.90   6.347870
235   11.25   9.312540
233    9.10   6.704036
146    0.52  -1.047441
237    2.00   2.579228
121    1.00   0.336746
224    5.25   4.283035
61    18.75  20.080464
229    9.25   6.704943
252    5.25   5.107695
2      7.25   6.949709
88     4.75   4.247505
116    1.10   1.247886
39     5.85   7.268472
11     6.85   8.046889
115    1.10   1.509372
189    0.20  -1.180848
151    0.50   0.141376
139    0.60   1.389646
230   11.45   9.911354
128    0.75   1.867025
14     2.25   2.251497
54     3.60   7.313261
25     4.15   3.379990
154    0.48   1.691561
216    6.45   5.342593
70     4.50   7.426432
102    1.35   2.168099
62    23.50  20.670493
103    1.35   1.660293
158    0.45  -0.517938
150    0.50  -0.040417
214    2.90   4.208466
275    9.70   7.677249
135    0.65   0.242558
293    8.55   9.145979
241    6.25   5.598552
182    0.25  -2.667023
200    4.40   4.260213
44     7.50   8.333602
173    0.38  -0.918060
126    0.80   1.918865
155    0.48   0.998146
273   10.90   9.676367
250    5.40   6.385957
123    0.90  -1.058103
52    16.00  15.816832
208    3.10   2.573677
22     2.50   2.803299
256    8.40   7.656383
41     1.95   1.962595

In [65]:
# new=pd.DataFrame([[2017, 12.5, 9000, 'Diesel', 'Dealer', 'Manual', 0]])
# new
new=pd.DataFrame([{'Year':2017, 'Present_Price':12.5, 'Kms_Driven':9000, 'Fuel_Type':'Diesel', 'Seller_Type':'Dealer', 'Transmission':'Manual', 'Owner':0}])
new

   Year  Present_Price  Kms_Driven Fuel_Type Seller_Type Transmission  Owner
0  2017           12.5        9000    Diesel      Dealer       Manual      0

In [66]:
new['no_of_year']=2025-new['Year']
new.drop('Year', inplace=True, axis=1)

In [67]:
new

,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,no_of_year
0,12.5,9000,Diesel,Dealer,Manual,0,8

In [68]:
new[oh.get_feature_names_out()]=oh.transform(new[['Fuel_Type', 'Seller_Type', 'Transmission']])

In [69]:
new.drop(['Seller_Type', 'Fuel_Type', 'Transmission'], inplace=True, axis=1)

In [70]:
new

,Present_Price,Kms_Driven,Owner,no_of_year,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Dealer,Seller_Type_Individual,Transmission_Automatic,Transmission_Manual
0,12.5,9000,0,8,0.0,1.0,0.0,1.0,0.0,0.0,1.0

In [72]:
#new[['Present_Price', 'Kms_Driven', 'no_of_year']] = sc.transform(new[['Present_Price', 'Kms_Driven', 'no_of_year']])
new[['no_of_year', 'Present_Price', 'Kms_Driven']]=sc.transform(new[['no_of_year', 'Present_Price', 'Kms_Driven']])

In [73]:
new

,Present_Price,Kms_Driven,Owner,no_of_year,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Petrol,Seller_Type_Dealer,Seller_Type_Individual,Transmission_Automatic,Transmission_Manual
0,0.579755,-0.716735,0,-1.170329,0.0,1.0,0.0,1.0,0.0,0.0,1.0

In [74]:
reg.predict(new)

array([10.00316098])